import type { Metadata } from "next";
import ConvexProvider from "@/components/ConvexProvider";
import "./globals.css";

export const metadata: Metadata = {
  title: "Pitch99 — You have 99 problems. But this p*tch ain't one.",
  description: "AI-powered 99-second pitch generator. Turn your product into a stunning pitch with market research, animated slides, and talking points. Built live at Founders Live Seattle.",
  metadataBase: new URL("https://pitch99.help"),
  openGraph: {
    title: "Pitch99 — AI-Powered 99-Second Pitch Generator",
    description: "Turn your product into a stunning pitch in minutes. Market research, animated slides, talking points, and Q&A prep — all generated by AI.",
    url: "https://pitch99.help",
    siteName: "Pitch99",
    type: "website",
    images: [
      {
        url: "/og-image.png",
        width: 1200,
        height: 630,
        alt: "Pitch99 — You have 99 problems. But this p*tch ain't one.",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "Pitch99 — AI-Powered 99-Second Pitch Generator",
    description: "Turn your product into a stunning pitch in minutes, not hours.",
    images: ["/og-image.png"],
  },
  keywords: ["pitch deck", "AI", "startup", "presentation", "99 seconds", "founders", "pitch generator"],
  authors: [{ name: "Adam Kovacs", url: "https://www.linkedin.com/in/adambkovacs/" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className="dark">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        <ConvexProvider>{children}</ConvexProvider>
      </body>
    </html>
  );
}
